using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Model.Migrations
{
    public partial class initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PRO2E_AUTH_LOGIN_USERs",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "text", nullable: false),
                    Version = table.Column<int>(type: "integer", nullable: false),
                    LoginName = table.Column<string>(type: "text", nullable: true),
                    Password = table.Column<string>(type: "text", nullable: true),
                    Comment = table.Column<string>(type: "text", nullable: true),
                    CreateDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    FullNameInChinese = table.Column<string>(type: "text", nullable: true),
                    FullNameInEnglish = table.Column<string>(type: "text", nullable: true),
                    Sex = table.Column<string>(type: "text", nullable: true),
                    ContactAddress = table.Column<string>(type: "text", nullable: true),
                    ContactZipCode = table.Column<string>(type: "text", nullable: true),
                    HousePhoneAreaCode = table.Column<string>(type: "text", nullable: true),
                    HousePhone = table.Column<string>(type: "text", nullable: true),
                    HouseOtherPhone = table.Column<string>(type: "text", nullable: true),
                    Email = table.Column<string>(type: "text", nullable: true),
                    SSID = table.Column<string>(type: "text", nullable: true),
                    Birthday = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Height = table.Column<int>(type: "integer", nullable: true),
                    Weight = table.Column<int>(type: "integer", nullable: true),
                    Blood = table.Column<string>(type: "text", nullable: true),
                    JobTitle = table.Column<string>(type: "text", nullable: true),
                    Mobile = table.Column<string>(type: "text", nullable: true),
                    ArrivedDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    LeaveDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    EmergencyContactPerson = table.Column<string>(type: "text", nullable: true),
                    EmergencyRelationship = table.Column<string>(type: "text", nullable: true),
                    EmergencyPhone = table.Column<string>(type: "text", nullable: true),
                    EmergencyAddress = table.Column<string>(type: "text", nullable: true),
                    UpdatedBy = table.Column<string>(type: "text", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    IsAlive = table.Column<int>(type: "integer", nullable: true),
                    IsLogin = table.Column<int>(type: "integer", nullable: true),
                    DisplayOrder = table.Column<string>(type: "text", nullable: true),
                    SecurityLevel = table.Column<int>(type: "integer", nullable: true),
                    IsCheckIP = table.Column<int>(type: "integer", nullable: true),
                    AssignBranchNo = table.Column<string>(type: "text", nullable: true),
                    InvaildDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    JobTitleId = table.Column<int>(type: "integer", nullable: true),
                    JobLevelId = table.Column<int>(type: "integer", nullable: true),
                    IdTypeId = table.Column<int>(type: "integer", nullable: true),
                    Is_MoreThan183Days = table.Column<int>(type: "integer", nullable: false),
                    IncomeCountryId = table.Column<int>(type: "integer", nullable: true),
                    TaxAgreementId = table.Column<int>(type: "integer", nullable: true),
                    Is_Married = table.Column<int>(type: "integer", nullable: false),
                    CountryId = table.Column<int>(type: "integer", nullable: true),
                    ProvinceId = table.Column<int>(type: "integer", nullable: true),
                    EducationId = table.Column<int>(type: "integer", nullable: true),
                    School = table.Column<string>(type: "text", nullable: true),
                    Specialty = table.Column<string>(type: "text", nullable: true),
                    Fax = table.Column<string>(type: "text", nullable: true),
                    Is_ClockIn = table.Column<int>(type: "integer", nullable: true),
                    CardNo = table.Column<string>(type: "text", nullable: true),
                    WorkingHourPerDay = table.Column<decimal>(type: "numeric", nullable: true),
                    EmployeeTypeId = table.Column<int>(type: "integer", nullable: true),
                    LeaveWithoutPayDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    CustomedField1 = table.Column<string>(type: "text", nullable: true),
                    CustomedField2 = table.Column<string>(type: "text", nullable: true),
                    HealthCheckupDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    EntryDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    ExpiryDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    StandardNo = table.Column<string>(type: "text", nullable: true),
                    PassportNo = table.Column<string>(type: "text", nullable: true),
                    Is_Foreign = table.Column<int>(type: "integer", nullable: true),
                    SubsidyId = table.Column<int>(type: "integer", nullable: true),
                    InsuranceIdentityId = table.Column<int>(type: "integer", nullable: true),
                    HCSpecialIdentity = table.Column<string>(type: "text", nullable: true),
                    LISpecialIdentity = table.Column<string>(type: "text", nullable: true),
                    LaborRetireSpecialIdentity = table.Column<string>(type: "text", nullable: true),
                    LINo = table.Column<string>(type: "text", nullable: true),
                    HCNo = table.Column<string>(type: "text", nullable: true),
                    HCNoWithholding = table.Column<string>(type: "text", nullable: true),
                    Is_PayRemittanceFee = table.Column<int>(type: "integer", nullable: true),
                    En_EDINotification = table.Column<int>(type: "integer", nullable: true),
                    DepartmentId = table.Column<int>(type: "integer", nullable: true),
                    SalaryDepartmentId = table.Column<int>(type: "integer", nullable: true),
                    p_SalarySubject = table.Column<int>(type: "integer", nullable: true),
                    EnglishJobTitle = table.Column<string>(type: "text", nullable: true),
                    p_SalaryPayMethod = table.Column<int>(type: "integer", nullable: true),
                    p_SalaryCaculateMethod = table.Column<int>(type: "integer", nullable: true),
                    BasicSalary = table.Column<int>(type: "integer", nullable: true),
                    p_TaxType = table.Column<int>(type: "integer", nullable: true),
                    TaxRate = table.Column<decimal>(type: "numeric", nullable: true),
                    LastEmployerContribution = table.Column<int>(type: "integer", nullable: true),
                    LastWorkerContribution = table.Column<int>(type: "integer", nullable: true),
                    Is_PaySalary = table.Column<int>(type: "integer", nullable: true),
                    Is_AttendanceBonus = table.Column<int>(type: "integer", nullable: true),
                    AttendanceBonus = table.Column<int>(type: "integer", nullable: true),
                    Is_MealAllowance = table.Column<int>(type: "integer", nullable: true),
                    MealAllowance = table.Column<int>(type: "integer", nullable: true),
                    Is_OverTimePay = table.Column<int>(type: "integer", nullable: true),
                    OverTimePayId = table.Column<int>(type: "integer", nullable: true),
                    Is_Welfare = table.Column<int>(type: "integer", nullable: true),
                    WelfareRate = table.Column<decimal>(type: "numeric", nullable: true),
                    p_EmployeeStatus = table.Column<int>(type: "integer", nullable: true),
                    DeputyId = table.Column<string>(type: "text", nullable: true),
                    Pic = table.Column<string>(type: "text", nullable: true),
                    NextAnnualLeaveAddingDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    p_HourPayBase = table.Column<int>(type: "integer", nullable: true),
                    CreatedBy = table.Column<string>(type: "text", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    Is_ReceiveFlowNotify = table.Column<int>(type: "integer", nullable: false),
                    InitOutDays = table.Column<int>(type: "integer", nullable: false),
                    SalaryBranchNo = table.Column<string>(type: "text", nullable: true),
                    ArrivedDateForPrint = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    PhysicianSpecialist = table.Column<string>(type: "text", nullable: true),
                    PhysicianCertificate = table.Column<string>(type: "text", nullable: true),
                    PersonalAnnualLeaveType = table.Column<int>(type: "integer", nullable: false),
                    Signature = table.Column<string>(type: "text", nullable: true),
                    DrLicNo = table.Column<string>(type: "text", nullable: true),
                    DrLicDrugNo = table.Column<string>(type: "text", nullable: true),
                    DrLicExclusiveNo = table.Column<string>(type: "text", nullable: true),
                    EducationDepartment = table.Column<string>(type: "text", nullable: true),
                    EducationStart = table.Column<string>(type: "text", nullable: true),
                    EducationEnd = table.Column<string>(type: "text", nullable: true),
                    EducationId2 = table.Column<int>(type: "integer", nullable: true),
                    EducationSchool2 = table.Column<string>(type: "text", nullable: true),
                    EducationDepartment2 = table.Column<string>(type: "text", nullable: true),
                    EducationStart2 = table.Column<string>(type: "text", nullable: true),
                    EducationEnd2 = table.Column<string>(type: "text", nullable: true),
                    ExperienceCompany1 = table.Column<string>(type: "text", nullable: true),
                    ExperienceTitle1 = table.Column<string>(type: "text", nullable: true),
                    ExperienceContent1 = table.Column<string>(type: "text", nullable: true),
                    ExperienceStart1 = table.Column<string>(type: "text", nullable: true),
                    ExperienceEnd1 = table.Column<string>(type: "text", nullable: true),
                    ExperienceCompany2 = table.Column<string>(type: "text", nullable: true),
                    ExperienceTitle2 = table.Column<string>(type: "text", nullable: true),
                    ExperienceContent2 = table.Column<string>(type: "text", nullable: true),
                    ExperienceStart2 = table.Column<string>(type: "text", nullable: true),
                    ExperienceEnd2 = table.Column<string>(type: "text", nullable: true),
                    ExperienceCompany3 = table.Column<string>(type: "text", nullable: true),
                    ExperienceTitle3 = table.Column<string>(type: "text", nullable: true),
                    ExperienceContent3 = table.Column<string>(type: "text", nullable: true),
                    ExperienceStart3 = table.Column<string>(type: "text", nullable: true),
                    ExperienceEnd3 = table.Column<string>(type: "text", nullable: true),
                    LicenseName1 = table.Column<string>(type: "text", nullable: true),
                    LicenseNo1 = table.Column<string>(type: "text", nullable: true),
                    LicenseName2 = table.Column<string>(type: "text", nullable: true),
                    LicenseNo2 = table.Column<string>(type: "text", nullable: true),
                    LicenseName3 = table.Column<string>(type: "text", nullable: true),
                    LicenseNo3 = table.Column<string>(type: "text", nullable: true),
                    DependentsCount = table.Column<int>(type: "integer", nullable: false),
                    InsuranceAmount = table.Column<int>(type: "integer", nullable: false),
                    Is_ElasticalHour = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PRO2E_AUTH_LOGIN_USERs", x => x.UserId);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PRO2E_AUTH_LOGIN_USERs");
        }
    }
}
